

import { useEffect, useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import html2pdf from 'html2pdf.js';

const FinalPage = () => {
  const [comparisonData, setComparisonData] = useState(null);
  const [userInfo, setUserInfo] = useState(null);
  const [activeTab, setActiveTab] = useState('original');
  const contentRef = useRef(null);
  const navigate = useNavigate();

  const handleDownload = () => {
    const element = contentRef.current;
    const opt = {
      margin: 1,
      filename: 'product-comparison-report.pdf',
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(element).save();
  };

  const renderStars = (rating) => {
    return "⭐".repeat(rating) + "☆".repeat(5 - rating);
  };

  useEffect(() => {
    // Get user info from localStorage or set default
    const user = JSON.parse(localStorage.getItem('user')) || {
      name: "John Doe",
      email: "john.doe@example.com"
    };
    setUserInfo(user);

    // Set default comparison data if none in localStorage
    const defaultData = {
      originalTitle: "Majestic Man Men's Comfort Regular Fit Checked Cotton Casual Shirt",
      originalPrice: 499.00,
      originalAsin: "B0D8ZLSMWK",
      originalImage: "https://m.media-amazon.com/images/I/71cFpnm0b6L._SX679_.jpg",
      originalRating: 4.5,
      originalReviews: 1250,
      
      competitorTitle: "Generic Men's Cotton Regular Fit Casual Checkered Shirt",
      competitorPrice: 449.00,
      competitorAsin: "B0D8ZLXXXX",
      competitorImage: "https://m.media-amazon.com/images/I/81nKjIkXbdL._SY741_.jpg",
      competitorRating: 4.2,
      competitorReviews: 850,

      similarityScore: 92,
      notes: "Both products show similar pattern and style. Original product has better fabric quality and stitching. Price difference is minimal. Original product has more positive customer reviews regarding durability.",
      
      // Additional product details
      brandComparison: {
        original: "Majestic Man",
        competitor: "Generic Brand"
      },
      features: [
        "Regular Fit",
        "Cotton Material",
        "Checkered Pattern",
        "Full Sleeves",
        "Casual Wear"
      ],
      sizes: ["S", "M", "L", "XL", "XXL"],
      colors: ["Blue", "Red", "Green", "Black"],
      deliveryDate: "Delivery by Oct 20, 2025"
    };

    const data = JSON.parse(localStorage.getItem('comparisonData')) || defaultData;
    setComparisonData(data);
  }, [navigate]);

  if (!comparisonData || !userInfo) {
    return (
      <div className="flex justify-center items-center h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-orange-500"></div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      <nav className="bg-[#131921] text-white px-4 py-2">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="text-2xl font-bold">Amazon</div>
          <div className="text-sm flex items-center gap-4">
            <span className="text-gray-300">Generated by {userInfo.name}</span>
            <button
              onClick={() => navigate('/seller-list')}
              className="bg-[#febd69] text-black px-4 py-1 rounded hover:bg-[#f3a847]"
            >
              Back to Dashboard
            </button>
          </div>
        </div>
      </nav>

      <div className="bg-[#232f3e] text-white px-4 py-2 mb-4">
        <div className="max-w-7xl mx-auto">
          <div className="text-sm">
            Similar Product Analysis
          </div>
        </div>
      </div>

      <div ref={contentRef} className="max-w-7xl mx-auto p-4">

        <div className="grid grid-cols-12 gap-6">
          {/* Left Column - Image */}
          <div className="col-span-5">
            <div className="sticky top-4">
              <div className="border p-4 mb-4">
                <div className="h-[500px] flex items-center justify-center bg-white">
                  <img
                    src={comparisonData?.competitorImage}
                    alt={comparisonData?.competitorTitle}
                    className="max-h-full max-w-full object-contain"
                  />
                </div>
              </div>

              <div className="bg-[#fef8f2] border border-[#f4d499] rounded p-3 mt-4">
                <div className="text-sm">
                  <span className="font-bold text-[#c45500]">Similarity Score: </span>
                  <span className="text-[#c45500]">{comparisonData?.similarityScore}% match with original product</span>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column - Product Details */}
          <div className="col-span-7">
            <div className="border-b border-[#e7e7e7] pb-4">
              <h1 className="text-xl font-medium mb-2">
                {comparisonData?.competitorTitle}
              </h1>
              <div className="flex items-center gap-2 text-sm">
                <div className="text-[#0F1111]">
                  <span className="text-[#007185] hover:text-[#c45500] cursor-pointer">
                    {comparisonData?.brandComparison.competitor}
                  </span>
                </div>
                <span className="text-[#707070]">|</span>
                <div className="flex items-center gap-1">
                  <span className="text-[#f2c200]">{renderStars(comparisonData?.competitorRating)}</span>
                  <span className="text-[#007185] hover:text-[#c45500] cursor-pointer">
                    {comparisonData?.competitorReviews} ratings
                  </span>
                </div>
              </div>
            </div>

            {/* Price Section */}
            <div className="py-4 border-b border-[#e7e7e7]">
              <div className="text-[#0F1111]">
                <span className="text-sm">Price:</span>
                <span className="text-[28px] text-[#0F1111] ml-2">
                  ${comparisonData?.competitorPrice}
                </span>
              </div>
              
              <div className="mt-1">
                <div className="inline-flex items-center bg-[#fef8f2] px-2 py-1 rounded">
                  <span className="text-sm text-[#c45500]">
                    {comparisonData?.competitorPrice < comparisonData?.originalPrice 
                      ? 'Lower price than original by '
                      : 'Higher price than original by '}
                    ${Math.abs(comparisonData?.originalPrice - comparisonData?.competitorPrice).toFixed(2)}
                  </span>
                </div>
              </div>
            </div>

            {/* Product Information */}
            <div className="py-4 border-b border-[#e7e7e7]">
              <table className="w-full text-sm">
                <tbody>
                  <tr>
                    <td className="py-1 pr-4 align-top text-[#565959]" style={{ width: '120px' }}>Brand</td>
                    <td className="py-1 text-[#0F1111]">{comparisonData?.brandComparison.competitor}</td>
                  </tr>
                  <tr>
                    <td className="py-1 pr-4 align-top text-[#565959]">ASIN</td>
                    <td className="py-1 text-[#0F1111]">{comparisonData?.competitorAsin}</td>
                  </tr>
                  <tr>
                    <td className="py-1 pr-4 align-top text-[#565959]">Rating</td>
                    <td className="py-1 text-[#0F1111]">
                      {comparisonData?.competitorRating} out of 5 ({comparisonData?.competitorReviews} reviews)
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

              {/* Features */}
              <div className="border-b border-[#e7e7e7] pb-4">
                <h3 className="text-[#0F1111] font-medium text-lg mb-2">About this item</h3>
                <ul className="list-disc pl-5 space-y-1 text-sm text-[#0F1111]">
                  {comparisonData?.features.map((feature, index) => (
                    <li key={index}>{feature}</li>
                  ))}
                </ul>
              </div>

              {/* Size & Color Options */}
              <div className="py-4 border-b border-[#e7e7e7]">
                <div className="mb-4">
                  <span className="text-sm font-medium text-[#0F1111]">Size: </span>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {comparisonData?.sizes.map((size, index) => (
                      <button
                        key={index}
                        className="min-w-[60px] px-3 py-1 border border-[#D5D9D9] rounded-lg text-sm
                        hover:border-[#007185] cursor-pointer"
                      >
                        {size}
                      </button>
                    ))}
                  </div>
                </div>
                <div>
                  <span className="text-sm font-medium text-[#0F1111]">Color: </span>
                  <div className="mt-2 flex flex-wrap gap-2">
                    {comparisonData?.colors.map((color, index) => (
                      <button
                        key={index}
                        className="min-w-[60px] px-3 py-1 border border-[#D5D9D9] rounded-lg text-sm
                        hover:border-[#007185] cursor-pointer"
                      >
                        {color}
                      </button>
                    ))}
                  </div>
                </div>
              </div>

              {/* Delivery & Analysis */}
              <div className="py-4 space-y-4">
                
                <div className="bg-[#F4F4F4] p-4 rounded">
                  <h3 className="text-[#0F1111] font-medium mb-2">Comparison Analysis</h3>
                  <p className="text-sm text-[#333333] leading-relaxed">{comparisonData?.notes}</p>
                </div>

                {/* Action Buttons */}
                <div className="flex flex-col gap-2 mt-6">
                  <button
                    onClick={handleDownload}
                    className="w-full bg-[#FFD814] hover:bg-[#F7CA00] text-[#0F1111] py-2 px-4 rounded-lg 
                    shadow-sm border border-[#FCD200]"
                  >
                    Download Comparison Report
                  </button>
                  <button
                    onClick={() => window.print()}
                    className="w-full bg-[#F0F2F2] hover:bg-[#DFE1E1] text-[#0F1111] py-2 px-4 rounded-lg
                    shadow-sm border border-[#D5D9D9]"
                  >
                    Print Report
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  )};

export default FinalPage;
